LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := OnePlusCamera

LOCAL_SRC_FILES := OnePlusCamera/OnePlusCamera.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_CERTIFICATE := platform


LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := OnePlusGallery

LOCAL_SRC_FILES := OnePlusGallery/OnePlusGallery.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_CERTIFICATE := platform


LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)